# render.yaml - Render Blueprint configuration

services:
  - type: web # Specifies a web service
    name: freelance-guys-landing # Name for the service in Render (you can change this)
    env: node # Specifies the environment (Node.js)
    plan: free # Specify your Render plan (e.g., free, starter, standard). Adjust if needed.
    rootDir: frontend # Sets the root directory for commands
    buildCommand: corepack enable && yarn install && yarn build # Build command including corepack fix
    startCommand: yarn run start # Start command using yarn run for PnP compatibility
    # Optional: Add health check path if your app has one (e.g., '/')
    # healthCheckPath: /
    # Optional: Add environment variables if needed
    # envVars:
    #   - key: NODE_ENV
    #     value: production
