
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom"; // Corrected import path
import { SuspenseWrapper } from "@/prod-components/SuspenseWrapper"; // Use path alias


const App = lazy(() => import("./pages/App.tsx"));
const Contact = lazy(() => import("./pages/Contact.tsx"));
const Pricing = lazy(() => import("./pages/Pricing.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <SuspenseWrapper><App /></SuspenseWrapper> },
	{ path: "/contact", element: <SuspenseWrapper><Contact /></SuspenseWrapper> },
	{ path: "/pricing", element: <SuspenseWrapper><Pricing /></SuspenseWrapper> },

];
